### ISSUE TITLE
c3 is not defined

### ISSUE THREAD

**Issue by keliangneu** [sunny0826/cms-grafana-builder#1]
配置datasource的时候提示c3 is not defined

**Comment by sunny0826** [comment]
@keliangneu 贴一下 DataSource 配置吧

**Comment by keliangneu** [comment]
Hello,

谢谢回复，配置信息如下：

[cid:image001.png@01D5B046.2E219610]

Regards
Ke Liang

**Comment by sunny0826** [comment]
这个图好像看不了...

**Comment by keliangneu** [comment]
可以添加你的叮叮吗

**Comment by sunny0826** [comment]
可以的，钉钉绑定的手机号，不方便发出来，可以扫钉钉的二维码添加
![image](https://user-images.githubusercontent.com/24563928/70677258-a0ccc500-1cc9-11ea-9f68-2f97dd5247ce.png)

其他联系方式见：https://guoxudong.io/publication/contact_me/

**Comment by keliangneu** [comment]
谢谢已经添加 请通过验证。

Regards
Ke Liang

**Comment by KXTX-DCOS** [comment]
c3这个是aliyun-cms-grafana更新ak加密导致的，需要把AK两个值通过base64 加密后 在填写才能正常

**Comment by uranus321** [comment]
@sunny0826 您好，grafana6.6.1 在CMS Grafana Service 中添加URL:http://metrics.cn-shenzhen.aliyuncs.com 提示HTTP Error Not Found，知道什么原因吗？
![CMS](https://user-images.githubusercontent.com/58728442/74085083-6d7f9a00-4ab0-11ea-9eda-7b3c2a99e556.jpg)

**Comment by sunny0826** [comment]
`c3 is not defined` 是由于[上游云监控插件 aliyun-cms-grafana](https://github.com/aliyun/aliyun-cms-grafana)更新，AK输入验证增加BASE64加解密功能导致，目前已修复
