### ISSUE TITLE
没有权限对granfan进行其他操作

### ISSUE THREAD

**Issue by kakaNo1** [sunny0826/cms-grafana-builder#14]
上一个版本我记得可以对grafana 进行导入模块什么的，最近的一版本是取消了吗？
第二个问题：
![image](https://user-images.githubusercontent.com/33709305/83376612-68e74480-a405-11ea-8ff9-b3ba4c3d6c2d.png)
这个流入流出，经过详细比对，发现反了，流入是流出，流出是流入，我想改下模板显示的名称，怎么修改

**Comment by sunny0826** [comment]
模块在 `model/eip.json` 里面

**Comment by sunny0826** [comment]
`dashboard` 里面的确实有误，已经修改了，之前版本是将其配置到 ConfigMap 里面的，但是 ConfigMap 大小有限制，所有将其移动到镜像中了
