### ISSUE TITLE
模板为什么不能选择数据源？官方有个：aliyun-cms-grafana？导入模板

### ISSUE THREAD

**Issue by blank-1** [sunny0826/cms-grafana-builder#15]

**Comment by sunny0826** [comment]
本项目就是官方grafanan插件的云原生解决方案，选择数据源需要先登录，项目为了方便展示开启了匿名访问的权限

**Comment by blank-1** [comment]
请问下数据存储是怎么样的，有木有保留监控项的数据

**Comment by sunny0826** [comment]
本项目只是对 aliyun-cms-grafana 插件的增强，由于云监控查询的监控项只有ID显示，没有资源的具体名称，所以结合阿里云 openapi 开发了本套解决方案，为了降低openapi 的调用，主机名称等信息会存在容器中的 sqlite 中，会随着容器的销毁而销毁

**Comment by blank-1** [comment]
https://api.aliyun.com/ 是这个吗？看了下，没有数据返回的，你是怎么做到基于open api metric数据的

**Comment by sunny0826** [comment]
数据源是我自己封装的一个，基于simpjson
![image](https://user-images.githubusercontent.com/24563928/84335627-da728000-abc7-11ea-988e-cd3aa83c1485.png)

**Comment by blank-1** [comment]
你是直接使用aliyun api的组件，实际是没办法收集metric数据做存储

**Comment by blank-1** [comment]
是如何收集数据的，有木有办法做存储

**Comment by sunny0826** [comment]
如果你想收集 metric 数据的话，可以使用 OpenAPI，是有开放给用户的，直接调用接口就能收集你想要的监控数据，存储就更简单了，找个数据库存就可以了

**Comment by blank-1** [comment]
求个地址？可以自己写个exporter

**Comment by sunny0826** [comment]
https://api.aliyun.com/#/?product=Cms 这不就是么，官网有文档
