### ISSUE TITLE
内存不显示问题

### ISSUE THREAD

**Issue by 21ki** [sunny0826/cms-grafana-builder#17]
![image](https://user-images.githubusercontent.com/24515576/86693310-24bb1580-c03d-11ea-9149-c9b79a2eff59.png)

**Comment by 21ki** [comment]
单个ECS可以看到 这个总dasnboard上面没有内存和硬盘得信息

**Comment by sunny0826** [comment]
看一下后端服务的日志，`cms-variable` 的日志

**Comment by 21ki** [comment]
![image](https://user-images.githubusercontent.com/24515576/86694466-37821a00-c03e-11ea-9aac-cebaf076bd60.png)

**Comment by 21ki** [comment]
别得没有看到其他错误

**Comment by sunny0826** [comment]
在 OpenAPI 页面调用一下，看看返回的结果，是不是有非ECS的阿里云探针传上去的，导致 instanceId 查询不到匹配的 ECS 名称
https://api.aliyun.com/?#/?product=Cms&version=2019-01-01&api=DescribeMetricTop&params={%22RegionId%22:%22cn-shanghai%22,%22Namespace%22:%22acs_ecs_dashboard%22,%22Orderby%22:%22Average%22,%22MetricName%22:%22memory_usedutilization%22}&tab=DOC&lang=PYTHON

**Comment by 21ki** [comment]
![image](https://user-images.githubusercontent.com/24515576/86696473-0f93b600-c040-11ea-9b8d-8ffc013bff39.png)

**Comment by sunny0826** [comment]
@21ki 注意保护自己的 AccessKey 和 AccessSecret，你的截图有有这些内容我帮你删除了

**Comment by 21ki** [comment]
好多，多谢哈

guoxudong <notifications@github.com> 于2020年7月7日周二 下午1:45写道：
