### ISSUE TITLE
提供新的模板

### ISSUE THREAD

**Issue by sunny0826** [sunny0826/cms-grafana-builder#2]
由于上游云监控插件 [ aliyun-cms-grafana](https://github.com/aliyun/aliyun-cms-grafana) 更新，增加了一些功能，将会在新版本中更新新模板

**Comment by kakaNo1** [comment]
Hello, could you please provide your grafanan template?Thank you very much

**Comment by sunny0826** [comment]
> Hello, could you please provide your grafanan template?Thank you very much

@kakaNo1 The template in this path: https://github.com/sunny0826/cms-grafana-builder/tree/master/model

**Comment by kakaNo1** [comment]
> > Hello, could you please provide your grafanan template?Thank you very much
> 
> @kakaNo1 The template in this path: https://github.com/sunny0826/cms-grafana-builder/tree/master/model

An error occurred when I imported the template,
![image](https://user-images.githubusercontent.com/33709305/79406301-491cce00-7fc9-11ea-8adf-ffec3bf163d1.png)

**Comment by kakaNo1** [comment]
> > > Hello, could you please provide your grafanan template?Thank you very much
> > 
> > 
> > @kakaNo1 The template in this path: https://github.com/sunny0826/cms-grafana-builder/tree/master/model
> 
> An error occurred when I imported the template,
> ![image](https://user-images.githubusercontent.com/33709305/79406301-491cce00-7fc9-11ea-8adf-ffec3bf163d1.png)

prompt 
“Templating init failed
Datasource named Variable DataSource was not found”

**Comment by sunny0826** [comment]
> > > > Hello, could you please provide your grafanan template?Thank you very much
> > > 
> > > 
> > > @kakaNo1 The template in this path: https://github.com/sunny0826/cms-grafana-builder/tree/master/model
> > 
> > 
> > An error occurred when I imported the template,
> > ![image](https://user-images.githubusercontent.com/33709305/79406301-491cce00-7fc9-11ea-8adf-ffec3bf163d1.png)
> 
> prompt
> “Templating init failed
> Datasource named Variable DataSource was not found”
I developed `DataSource` for this `Dashboard`, so I can't import it directly, I need to install the `DataSource`.

**Comment by kakaNo1** [comment]
Ok, thank you very much for your timely reply. Doesn't DataSource directly pull the data of ali cloud?So, how do I sit now?

**Comment by sunny0826** [comment]
> Ok, thank you very much for your timely reply. Doesn't DataSource directly pull the data of ali cloud?So, how do I sit now?

This DataSource accesses the aliyun CMS OpenAPI for monitoring metrics. This repo is a helm chart. You need `helm intsall` this chart to your k8s cluster. For more information read https://github.com/sunny0826/cms-grafana-builder/blob/master/README_CN.md

**Comment by kakaNo1** [comment]
> > 好的，非常感谢您的及时答复。DataSource不直接提取阿里云的数据吗？那我现在怎么坐？
> 
> 该数据源访问aliyun CMS OpenAPI来监控指标。此回购是一张舵图。您需要`helm intsall`将此图表添加到k8s集群。有关更多信息，请阅读https://github.com/sunny0826/cms-grafana-builder/blob/master/README_CN.md

好的，非常感谢你的及时回复，我用的docker部署grafana ，然后安装了aliyun-cms-grafana（https://github.com/aliyun/aliyun-cms-grafana.git ）插件，应该是一样的？
![image](https://user-images.githubusercontent.com/33709305/79411490-85eec200-7fd5-11ea-9de8-48134b46c017.png)
![image](https://user-images.githubusercontent.com/33709305/79411513-92731a80-7fd5-11ea-846d-246f2041c15f.png)
There is some data available：
![image](https://user-images.githubusercontent.com/33709305/79411538-a74fae00-7fd5-11ea-839a-cefe3d6d687a.png)

**Comment by sunny0826** [comment]
差不多，但是CMS的API只能获取ECS的ID，没法获取ECS等资源的name，所以我写了一个DataSource来获取name，包括这里的TOP10都是通过datasource来获取CMS OpenAPI 的信息

**Comment by kakaNo1** [comment]
Wow, I've been confused before, this id is so confusing, I can't see the specific alias,I'll try it with Helm

**Comment by kakaNo1** [comment]
I'm sorry, I found that we only have docker environment online, and we cannot use helm or K8S at present. Can I directly use docker to complete this?

**Comment by sunny0826** [comment]
本项目是采用helm的解决方案，如果采用docker的话，需要摘除自定义的DataSource，你可以再提一个issue，应为涉及到比较敏感的 AS/AK ，所以采用的k8s的secret来存储，如果想只使用docker的，你可以提一个新issue，在那个issue中讨论
