### ISSUE TITLE
top 1 可以改成top10或者自定义么？

### ISSUE THREAD

**Issue by froglian** [sunny0826/cms-grafana-builder#20]
仔细研读了一下配置文件，好像没有找到哪里可以修改dashboard里面top 几的修改，这块可以开放修改或者能如何修改下么？多谢！

**Comment by sunny0826** [comment]
top几的修改？我不是很明白，我记得我只做了 CPU 内存 和 磁盘的 top10，这些接口都是阿里云开放出来的，其他指标有没有我就不清楚了

**Comment by sunny0826** [comment]
top1 改 top10 是都展示，还是只展示 top10?

**Comment by froglian** [comment]
![image](https://user-images.githubusercontent.com/16535660/118784809-e6c88800-b8c2-11eb-9783-e77c2bc0640d.png)
是这样，是说，比如左上角CPU top 1这个panel，如果我希望展示CPU top10，就是cpu最高的前10个ECS,这个在哪里修改呢？我看了下dashboard的json file，没有找到

**Comment by sunny0826** [comment]
这个只展示 top1 一个数据，这个接口是我自定义的数据源，只有 top1 一个值，如果要 top10 需要改代码

**Comment by froglian** [comment]
自定义数据源在哪能改一下？可以指示下不？我研究下看看我能不能自己改改，谢谢

**Comment by sunny0826** [comment]
你可以在 grafana 上 edit 一下看看他的数据源是哪个，如果是 sample json 那就是自定义数据源，在 python 代码里找

**Comment by froglian** [comment]
主要是grafana那里不像默认的有edit按钮，没有edit。这种是不是应该是python里封装好了的？
![image](https://user-images.githubusercontent.com/16535660/118786230-2e9bdf00-b8c4-11eb-89c0-fc798061583b.png)

**Comment by sunny0826** [comment]
这是权限问题吧，你要先登录

**Comment by froglian** [comment]
是说登陆什么呢？我部署好服务后，点击会要求登陆grafana，输入了账号密码以后，就进入控制太，然后进入dashboard，看到的就是这个，还有其他地方需要登陆么？
![image](https://user-images.githubusercontent.com/16535660/118795719-770bca80-b8cd-11eb-8afd-3edcbef97886.png)

**Comment by sunny0826** [comment]
那应该可以 edit 的呀

**Comment by froglian** [comment]
确实不行....
![image](https://user-images.githubusercontent.com/16535660/118806895-349cba80-b8da-11eb-98b0-501f7f0c0ff2.png)

**Comment by sunny0826** [comment]
好像 json 生成的 dashboaed 不能编辑...试试 explore

**Comment by froglian** [comment]
奥这样，已经可以啦，多谢~
