### ISSUE TITLE
能否直接使用docker部署

### ISSUE THREAD

**Issue by kakaNo1** [sunny0826/cms-grafana-builder#7]
线上没有helm和K8S环境，想直接用docker部署此项目

**Comment by sunny0826** [comment]
我这边抽空改一下

**Comment by sunny0826** [comment]
@kakaNo1 需要datasource的功能吗？还是只要grafana展示就可以？

**Comment by kakaNo1** [comment]
> @kakaNo1 需要datasource的功能吗？还是只要grafana展示就可以？

展示

**Comment by kakaNo1** [comment]
https://github.com/aliyun/aliyun-cms-grafana.git 项目展示id，而我们想直接展示出来机器别名

**Comment by sunny0826** [comment]
目前只能做到基于机器别名选择，ID在图标里展示的还是id

**Comment by kakaNo1** [comment]
> 目前只能做到基于机器别名选择，ID在图标里展示的还是id

选择上能用别名区别，就已经很棒了

**Comment by sunny0826** [comment]
嗯嗯，那就等等吧，刚才看了一下代码，都搞到docker里面还是有些难度的

**Comment by kakaNo1** [comment]
我本地有K8S环境，我先研究下你这个，非常感谢大佬的及时回复以及你做的贡献

**Comment by sunny0826** [comment]
@kakaNo1 已发布，详见 https://github.com/sunny0826/cms-grafana-builder/blob/master/README_CN.md
`# 快速开始`

**Comment by kakaNo1** [comment]
镜像 guoxudongdocker/grafana-cms-run:0.2.1-release  是否已经公开？

**Comment by sunny0826** [comment]
公开的，已经上传 dockerhub 了，昨天弄完我测了一下是可以用的
