### ISSUE TITLE
下面不知道该怎么配置了，麻烦大神指点下！

### ISSUE THREAD

**Issue by vuzemin** [sunny0826/cms-grafana-builder#8]
sunny，您好！
有问题请教您。
1、第一步按照上面的步骤安装启动了my-release实例
命令如下：
helm install my-release cms-grafana-0.3.0.tgz \
--set access_key_id=xxx \
--set access_secret=xxx \
--set region_id=cn-beijing \
--set password=xxx

提示这个：
Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods -l "app=cms-grafana,release=my-release" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80
2、按照上面的命令在本地执行，报错了，我就没使用变量的方式转发端口，我直接手动配置的
kubectl port-forward  my-release-cms-variable-95fdb84f4-qszcv  80:8088
进入pod里面只看到启动了8088端口，我就试着将8088端口转发到80，本地访问显示结果为UP
卡在这一步了，不知道要怎么配置，麻烦sunny大神帮我看下，谢谢！

**Comment by sunny0826** [comment]
` my-release-cms-variable`这个是后端服务是用来对接云监控API的...不用去管，你要访问的是grafana，应该是一个叫做`my-release-cms-grafana`的 deployment，直接使用下面这个命令就行了：

```bash
kubectl port-forward deployment/my-release-cms-grafana 8080:8080
```

然后访问 http://localhost:8080 就行了

**Comment by sunny0826** [comment]
@vuzemin 按上面的方法应该就能访问了

**Comment by vuzemin** [comment]
本地访问：curl  http://127.0.0.1:8080
<a href="/login">Found</a>. 出现了这个，应该是可以了，但是除了本机，其他机器无法访问，端口映射可以改为0.0.0.0吗？

**Comment by sunny0826** [comment]
> 本地访问：curl http://127.0.0.1:8080
> [Found](/login). 出现了这个，应该是可以了，但是除了本机，其他机器无法访问，端口映射可以改为0.0.0.0吗？

@vuzemin 其他机器访问？建议使用 ingress

**Comment by vuzemin** [comment]
意思是其他机器是无法telnet通这个8080端口，因为端口是绑定再127.0.0.1，不是绑定在本机IP上，所以在浏览器通过IP是无法访问了8080这个端口的

**Comment by vuzemin** [comment]
只能在服务器上访问8080端口，如果在一个内网的其他机器上访问8080端口是不同，防火墙放行了这个8080端口。

**Comment by sunny0826** [comment]
你的集群如果部署带内网，可以使用 nodeport 来设置，把 svc 的配置改了就好

**Comment by vuzemin** [comment]
好的，我对K8S,还不是太熟，我试试。
另外，有个问题，只能配置一个aliyun帐号吗？ 例如我们公司是分了多个aliyun帐号的

**Comment by sunny0826** [comment]
建议单独给他配置一个子账号，并且只开放只读权限，并没有支持多账号的计划

**Comment by vuzemin** [comment]
好的，谢谢您的回复！目前是使用的子账号，为了安全。希望后面可以增加多账号。
